DATA:
  BATCH_SIZE: 512
MODEL:
  TYPE: gmlp
  NAME: gmlp_s_ta
  DROP_PATH_RATE: 0.05
  GMLP:
    ATTENTION: True 
TRAIN:
  ACCUMULATION_STEPS: 0
  BASE_LR: 0.001
  WARMUP_LR: 0.000001 
  MIN_LR: 0.00001
  WEIGHT_DECAY: 0.05
  WARMUP_EPOCHS: 32 
  CLIP_GRAD: 1.0
  LR_SCHEDULER:
    NAME: 'cosine'
  OPTIMIZER:
    NAME: 'adamw'
    EPS: 0.000001
AUG:
  REPROB: 0.