DATA:
  BATCH_SIZE: 128 #18G
MODEL:
  TYPE: mixer
  NAME: mixer_s16_224
  DROP_PATH_RATE: 0.1
  MIXER:
    NUM_BLOCKS: 12
    PATCH_SIZE: 16
    HIDDEN_DIM: 512
TRAIN:
  ACCUMULATION_STEPS: 0
  BASE_LR: 0.001
  WARMUP_LR: 0.000001 
  MIN_LR: 0.00001
  WEIGHT_DECAY: 0.05
  WARMUP_EPOCHS: 5 
  CLIP_GRAD: 5.0 # swin
  LR_SCHEDULER:
    NAME: 'cosine'
  OPTIMIZER:
    NAME: 'adamw'