DATA:
  BATCH_SIZE: 128 #18G
MODEL:
  TYPE: mixer
  NAME: mixer_b16_224
  DROP_PATH_RATE: 0.1
  MIXER:
    NUM_BLOCKS: 12
    PATCH_SIZE: 16
    HIDDEN_DIM: 768
TRAIN:
  ACCUMULATION_STEPS: 2
  BASE_LR: 0.001
  WARMUP_LR: 0.000001 # deit
  MIN_LR: 0.00001 # deit
  WEIGHT_DECAY: 0.1
  WARMUP_EPOCHS: 32 # 4096 10k
  CLIP_GRAD: 1.0
  LR_SCHEDULER:
    NAME: 'linear'
  OPTIMIZER:
    NAME: 'adam'
AUG:
  AUTO_AUGMENT: 'rand-m15-mstd0.5-inc1'
  MIXUP: 0.5